ARG MAVEN_VERSION="3.9.11"
ARG MAVEN_BASE_URL="https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries"

FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-21 AS build-step
ARG MAVEN_VERSION
ARG MAVEN_BASE_URL
USER root
WORKDIR /app
# RUN gu install native-image
RUN microdnf install git -y
RUN git clone https://github.com/sunye/correctexam-backend.git
WORKDIR /app/corrigeExamBack
RUN git checkout develop
WORKDIR /app/corrigeExamBack

RUN mkdir -p /opt/maven
WORKDIR /opt/maven


RUN echo
RUN curl -fsSL -o /tmp/apache-maven.tar.gz ${MAVEN_BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz && tar -xzf /tmp/apache-maven.tar.gz && rm -f /tmp/apache-maven.tar.gz

WORKDIR /app/corrigeExamBack
RUN /opt/maven/apache-maven-${MAVEN_VERSION}/bin/mvn --settings .util/settings.xml package -Pnative

FROM quay.io/quarkus/quarkus-micro-image:2.0-amd64 as prod
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --from=build-step /app/corrigeExamBack/target/*-runner /work/application
# COPY --chown=1001:root ./src/main/resources/db/migration/ /work/migration
EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.datasource.jdbc.url=jdbc:mysql://correctexam-mysql:3306/correctexam?useUnicode=true&characterEncoding=utf8&useSSL=false"]
#, "-Dquarkus.flyway.locations=filesystem:/work/migration/"]


